// Generated by CoffeeScript 1.4.0
(function() {

  define(['src/js/person'], function(Person) {
    return describe('Person', function() {
      return it('', function() {});
    });
  });

}).call(this);
