// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var Person;
    return Person = (function() {

      function Person(name) {
        this.name = name != null ? name : "Joe";
      }

      return Person;

    })();
  });

}).call(this);
